CREATE TABLE MEMBERS (
    ID BIGINT PRIMARY KEY,
    FirstName VARCHAR(100),
    LastName VARCHAR(100),
    Phone VARCHAR(50),
    SecondPhone VARCHAR(50),
    Email VARCHAR(255),
    SecondEmail VARCHAR(255),
    DateOfBirth DATE,
    Address VARCHAR(255),
    City VARCHAR(100),
    State VARCHAR(100),
    Country VARCHAR(50),
    ZipCode VARCHAR(20),
    Gender VARCHAR(10),
    MemberType VARCHAR(50),
    Membership VARCHAR(255),
    Contacts TEXT,
    Status VARCHAR(50),
    JoinedDate DATE,
    LastPaymentDate DATE,
    Notes TEXT,
    ValidFrom TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ValidTo TIMESTAMP DEFAULT '9999-12-31 23:59:59',
    PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo)
) WITH (SYSTEM_VERSIONING = ON);
